mutation upsert_task($objects: [sub_task_insert_input!]!) {
  insert_sub_task(objects: $objects, on_conflict: {constraint: sub_task_pkey, update_columns: [
    task_title,
    task_description,
    task_time_estimate,
    created_at,
    parent_task_id
  ]}) {
    returning {
      id
      task_title
      task_description
      task_time_estimate
      created_at
      parent_task_id
    }
  }
}
